language: csharp
solution: csharp-example-project.sln
mono: none
dotnet: 2.0.0
os: linux
dist: trusty
sudo: false
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
script:
  - dotnet restore
  - cd ./Tests/ && dotnet test
 